[package]
name = "rusty_dra_chan"
version = "0.1.1"
edition = "2021"

[dependencies]
poise = "0.3.0"
tokio = { version = "1.4.0", features = ["macros", "rt-multi-thread"] }
sea-orm = { version = "^0", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros", "debug-print", "mock" ] }

